### ISSUE TITLE
installation/startup error if project table not created first

### ISSUE THREAD

**Issue by asah** [tracyhenry/Kyrix#42] opened 2018-11-14 02:49 UTC
Ubuntu 16.04, Postgres 10.0, NodeJS v8.12.0, Maven (mvn) 3.3.9, Java 8, 

The setup instructions read: "Go to tile-server/. Run mvn compile to build the server. Run mvn exec:java -Dexec.mainClass="main.Main" to start the server. After the server starts, it will prompt that it did not find the spec of the app and is waiting for it..." and then "cd compiler/examples/nba; node nba.js"

This results in "kyrix@kyrix ERROR:  relation "project" does not exist at character 21" (seen in postgres logs). The bad SQL: select content from project where name = 'nba'

Perhaps the best workaround is to manually create the table using this idempotent SQL:
CREATE TABLE IF NOT EXISTS project (name VARCHAR(255), content TEXT, dirty int, CONSTRAINT PK_project PRIMARY KEY (name));

**Comment by tracyhenry** [comment] 2018-11-15 02:33
The error is actually in the backend: https://github.com/tracyhenry/Kyrix/blob/master/tile-server/src/main/java/main/Main.java#L95

This function tries to read the spec from DB (e.g.  `select from project where name = 'nba'`)when the server is started. If no spec has ever been run, this will throw an exception since the `project` relation does not exist yet. This is fine actually - because we caught and ignored the exception.

The point at which the bug really happened was when you run a spec (e.g. `node nba.js`). The backend  then tried to do an update to the project relation: https://github.com/tracyhenry/Kyrix/blob/master/tile-server/src/main/java/main/Main.java#L68. This SQL update is still fine, but the problem is that it was run within the same transaction that the last failed select query was run in. PostgreSQL thought you were playing with fire thus [aborted this transaction](https://stackoverflow.com/questions/10399727/psqlexception-current-transaction-is-aborted-commands-ignored-until-end-of-tra). 

The fix is to commit the transaction of the first select query. See this [commit](https://github.com/tracyhenry/Kyrix/commit/5c0c5d9f14929111ed05607558f42a88e182b169). It fixes the bug on my end. Can you test on the docker image then we can close this issue.

**Comment by asah** [comment] 2018-11-15 08:08
tested - works!

**Comment by tracyhenry** [comment] 2018-11-15 14:55
Thanks!

**Closed by tracyhenry** 2018-11-15 14:55 UTC
